// src/routes/(about)/technologies.svelte
<script>
  import { IconText } from "$lib/components";
  import {
    SiSvelte,
    SiTypescript,
    SiReact,
    SiNextdotjs,
    SiTailwindcss,
    SiDrizzle,
    SiJest,
    SiVitest,
    SiPytorch,
    SiPython,
    SiNixos,
    SiCplusplus,
    SiC,
    SiLua,
    SiRust,
    SiGnubash,
    SiGit,
    SiArchlinux,
    SiNeovim,
    SiGithubactions,
    SiMantine,
    SiTypst,
  } from "@icons-pack/svelte-simple-icons";

  const webTech = [
    { icon: SiSvelte, label: "Svelte" },
    { icon: SiReact, label: "React" },
    { icon: SiNextdotjs, label: "Next.js" },
    { icon: SiTailwindcss, label: "TailwindCSS" },
    { icon: SiDrizzle, label: "Drizzle" },
    { icon: SiJest, label: "Jest" },
    { icon: SiVitest, label: "Vitest" },
    { icon: SiMantine, label: "Mantine" },
  ];

  const aiTech = [
    { icon: SiPytorch, label: "PyTorch" },
    { icon: null, label: "Optuna" },
  ];

  const langProTech = [
    { icon: SiPython, label: "Python" },
    { icon: SiNixos, label: "Nix" },
    { icon: null, label: "Java" },
    { icon: SiRust, label: "Rust" },
    { icon: SiTypescript, label: "TypeScript" },
  ];

  const langAcqTech = [
    { icon: SiLua, label: "Lua" },
    { icon: SiC, label: "C" },
    { icon: SiCplusplus, label: "C++" },
    { icon: SiGnubash, label: "Bash" },
  ];

  const ciCdTech = [{ icon: SiGithubactions, label: "GitHub Actions" }];

  const osTech = [
    { icon: SiNixos, label: "NixOS" },
    { icon: SiArchlinux, label: "Arch Linux" },
  ];

  const miscTech = [
    { icon: SiGit, label: "Git" },
    { icon: SiNeovim, label: "Neovim" },
    { icon: SiTypst, label: "Typst" },
  ];
</script>

{#snippet iconSet(items)}
  {#each items as item (item.label)}
    {#snippet icon()}{#if item.icon}<item.icon size="16" />{/if}{/snippet}
    <IconText icon={item.icon ? icon : undefined} label={item.label} />
  {/each}
{/snippet}

<div class="root">
  <div class="adaptive-row">
    <div class="adaptive-cell">
      Web:
      <div class="icon-group">{@render iconSet(webTech)}</div>
    </div>

    <div class="adaptive-cell">
      Machine learning / artificial intelligence:
      <div class="icon-group">{@render iconSet(aiTech)}</div>
    </div>
  </div>

  <div class="adaptive-row">
    <div class="adaptive-cell">
      Languages (proficient):
      <div class="icon-group">{@render iconSet(langProTech)}</div>
    </div>

    <div class="adaptive-cell">
      Languages (acquainted):
      <div class="icon-group">{@render iconSet(langAcqTech)}</div>
    </div>
  </div>

  <div class="adaptive-row">
    <div class="adaptive-cell">
      Continuous development / continuous integration:
      <div class="icon-group">{@render iconSet(ciCdTech)}</div>
    </div>

    <div class="adaptive-cell">
      Operating systems:
      <div class="icon-group">{@render iconSet(osTech)}</div>
    </div>
  </div>

  <div class="adaptive-row">
    <div class="adaptive-cell">
      Miscellaneous:
      <div class="icon-group">{@render iconSet(miscTech)}</div>
    </div>
  </div>
</div>

<style>
  .root {
    display: flex;
    flex-direction: column;
    gap: 1.5em;
  }

  .adaptive-row {
    gap: 1.5em 1em;
  }

  .icon-group {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    gap: 8px;

    margin-top: 8px;
  }
</style>

// src/components/Technologies.vue
<script setup lang="ts">
  import * as simpleIcons from "simple-icons";
  import type { SimpleIcon } from "simple-icons";

  import { Badge, IconText } from "@/components";
  import { Box, Grid, Stack, Cluster } from "@/components/primitives";
  import { FALLBACK_LANG_COLOR, getLanguageColor } from "@/utils/languages";

  type Tech = {
    icon: string | null;
    label: string;
  };

  const techData: Record<string, Tech[]> = {
    Web: [
      { icon: "simple-icons:vuedotjs", label: "Vue.js" },
      { icon: "simple-icons:nuxt", label: "Nuxt" },
      { icon: "simple-icons:svelte", label: "Svelte" },
      { icon: "simple-icons:react", label: "React" },
      { icon: "simple-icons:nextdotjs", label: "Next.js" },
      { icon: "simple-icons:tailwindcss", label: "TailwindCSS" },
      { icon: "simple-icons:drizzle", label: "Drizzle" },
      { icon: "simple-icons:jest", label: "Jest" },
      { icon: "simple-icons:vitest", label: "Vitest" },
      { icon: "simple-icons:mantine", label: "Mantine" },
    ],

    "Machine learning / artificial intelligence": [
      { icon: "simple-icons:pytorch", label: "PyTorch" },
      { icon: null, label: "Optuna" },
    ],

    "Languages (proficient)": [
      { icon: "simple-icons:python", label: "Python" },
      { icon: "simple-icons:nixos", label: "Nix" },
      { icon: "devicon-plain:java", label: "Java" },
      { icon: "simple-icons:rust", label: "Rust" },
      { icon: "simple-icons:typescript", label: "TypeScript" },
    ],

    "Languages (acquainted)": [
      { icon: "simple-icons:lua", label: "Lua" },
      { icon: "simple-icons:c", label: "C" },
      { icon: "simple-icons:cplusplus", label: "C++" },
      { icon: "simple-icons:gnubash", label: "Bash" },
    ],

    "Continuous integration / continuous deployment": [
      { icon: "simple-icons:githubactions", label: "GitHub Actions" },
    ],

    "Operating systems": [
      { icon: "simple-icons:nixos", label: "NixOS" },
      { icon: "simple-icons:archlinux", label: "Arch Linux" },
    ],

    Miscellaneous: [
      { icon: "simple-icons:git", label: "Git" },
      { icon: "simple-icons:neovim", label: "Neovim" },
      { icon: "simple-icons:typst", label: "Typst" },
    ],
  };

  function getIconColor(tech: Tech): string | null {
    if (!tech.icon) {
      return null;
    }

    const color = getLanguageColor(tech.label);
    if (color !== FALLBACK_LANG_COLOR) {
      return color;
    }

    if (tech.icon.startsWith("simple-icons:")) {
      const slug = tech.icon.slice("simple-icons:".length);
      const cSlug = slug[0].toUpperCase() + slug.slice(1);
      const entryName = `si${cSlug}`;
      if (entryName in simpleIcons) {
        const iconData = simpleIcons[entryName as keyof typeof simpleIcons] as SimpleIcon;
        return `#${iconData["hex"]}`;
      }
    }

    return FALLBACK_LANG_COLOR;
  }
</script>

<template>
  <Box
    paddingInline="var(--space-m)"
    paddingBlock="var(--space-m)"
    label="Technologies and Skills"
    labelComponent="h1"
  >
    <Grid
      target-min-width="25rem"
      gap="var(--space-l)"
    >
      <Stack
        v-for="[cat, values] in Object.entries(techData)"
        gap="0.5em"
      >
        <p :class="$style.categoryLabel">{{ cat }}:</p>
        <Cluster
          columnGap="var(--space-xs)"
          rowGap="var(--space-xs)"
        >
          <Badge v-for="{ icon, label } in values">
            <IconText
              :icon="icon"
              :iconColor="getIconColor({ icon, label }) ?? undefined"
              >{{ label }}</IconText
            >
          </Badge>
        </Cluster>
      </Stack>
    </Grid>
  </Box>
</template>

<style module>
  .categoryLabel {
    text-align: left;
  }
</style>
