// src/components/primitives/Stack.vue
<script setup lang="ts">
  const {
    gap = "var(--space-s)",
    direction = "column",
    alignItems = "normal",
  } = defineProps<{
    gap?: string;
    direction?: "column" | "row";
    alignItems?: string;
  }>();
</script>

<template>
  <div :class="$style.stack">
    <slot />
  </div>
</template>

<style module>
  .stack {
    display: flex;
    flex-direction: v-bind(direction);
    justify-content: flex-start;
    align-items: v-bind(alignItems);
    gap: v-bind(gap);
  }
</style>

// src/lib/components/Stack.svelte
<script>
  const { class: className = "", style = "", children } = $props();
</script>

<div class="stack {className}" {style}>{@render children()}</div>

<style>
  .stack {
    display: flex;
    flex-direction: column;
    align-items: var(--align, stretch);
    justify-content: var(--justify, flex-start);

    gap: var(--gap, 8px);
    padding: var(--padding, 0);
  }
</style>
